server:
  port: 31066
spring:
  application:
    name: myhrm-company
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://218.90.184.132:3306/dev_db?characterEncoding=utf8&useSSL=false
    username: root
    password: lixcxMYSQL(2018)
  jpa:
    database: mysql
    show-sql: true
    open-in-view: true